general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para bloquear
    before_sleep_cmd = loginctl lock-session    # Bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Encender pantalla al despertar
}

listener {
    timeout = 300                                # 5 minutos
    on-timeout = loginctl lock-session           # Bloquea la sesión
}

listener {
    timeout = 330                                # 5.5 minutos
    on-timeout = hyprctl dispatch dpms off       # Apaga la pantalla
    on-resume = hyprctl dispatch dpms on         # La enciende al volver
}

listener {
    timeout = 600                                # 10 minutos
    on-timeout = systemctl suspend               # Suspende el equipo
}
