[General]
CurrentTheme = lotos
IconSize = 24
Position = bottom
Exclusive = true
SmartView = false
AutoHideDelay = 200
Margin = 8
Padding = 2
Radius = 10
Opacity = 0.8
NoLauncher = true
Layer = top

[Theme]
Spacing = 6

[PinnedApps]
Apps = kitty
