[General]
CurrentTheme = lotos
IconSize = 28
Position = bottom
Exclusive = true
SmartView = false
AutoHideDelay = 200
Margin = 8
Padding = 4
Radius = 12
Opacity = 0.8
NoLauncher = true
Layer = top

[Theme]
Spacing = 6

[PinnedApps]
Apps = kitty,chromium,vesktop,org.telegram.desktop
